export const AUTH_STATE_SUCCESS = "AUTH_STATE_SUCCESS";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_LOGGED_IN = "USER_LOGGED_IN";

export const SERVER_ERROR = "SERVER_ERROR";
export const HIDE_CUSTOM_ERROR = "HIDE_CUSTOM_ERROR";
export const SHOW_CUSTOM_ERROR = "SHOW_CUSTOM_ERROR";

export const SET_FILTERS = "SET_FILTERS";

export const SET_FEATURED_DETAILS = "SET_FEATURED_DETAILS";

export const DONATION_PARTNERS_RECEIVED = "DONATION_PARTNERS_RECEIVED";
export const DONATE_DETAILS_RECEIVED = "DONATE_DETAILS_RECEIVED";

export const RSS_FEEDS_RECEIVED = "RSS_FEEDS_RECEIVED";

export const CATEGORIES_RECEIVED = "CATEGORIES_RECEIVED";

export const USER_CHANGE_PASSWORD = "USER_CHANGE_PASSWORD";
export const USER_CHANGE_EMAIL = "USER_CHANGE_EMAIL";
export const USER_CHANGE_NAME = "USER_CHANGE_NAME";

export const USER_GET_SELF = "USER_GET_SELF";
