export const AUTH_STATE_SUCCESS = "AUTH_STATE_SUCCESS";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_LOGGED_IN = "USER_LOGGED_IN";

export const SERVER_ERROR = "SERVER_ERROR";
export const HIDE_CUSTOM_ERROR = "HIDE_CUSTOM_ERROR";
export const SHOW_CUSTOM_ERROR = "SHOW_CUSTOM_ERROR";

export const SET_FILTERS = "SET_FILTERS";

export const SET_FEATURED_DETAILS = "SET_FEATURED_DETAILS";
export const SET_DONATE_DETAILS = "SET_DONATE_DETAILS";
